### ISSUE TITLE
Support workspace?

### ISSUE THREAD

**Issue by suyulin** [gokins/gokins#27]
hi,
Previous version support

**Comment by mgr9525** [comment]
还是支持的，地址栏可以填git地址也可以填 目录路径，每个stage与step都可以用repo重新定义命令目录(pwd)

**Comment by mgr9525** [comment]
stages:
  - step: xxxx
    repo: /home

**Comment by suyulin** [comment]
How to cache node_modules dir?

**Comment by mgr9525** [comment]
目前还没有cache的规划，因为我大部分时间使用本地目录pull模式。
不过这是一个好建议，我后期可以加上这个功能。
可以给你个建议
1. 每次npm i之后把 node_modules cp到节点机上
2. 每次npm i之前把 node_modules cp回来
3. 控制好权限，应该也不会造成很大的问题

**Comment by suyulin** [comment]
> 

thx
